name: my_pharmacy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  intl: ^0.20.2
  hexcolor: ^3.0.1
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  flutter_conditional_rendering: ^2.1.0
  conditional_builder_null_safety: ^0.0.6
  dio: ^5.8.0+1
  http: ^0.13.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.4+4
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  fluttertoast: ^8.2.12
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/